### ISSUE TITLE
Q: Target and linked

### ISSUE THREAD

**Issue by renatomefi** [rtuin/pla#7]
Question:

Is it possible to target a linked target?

``` yml
vagrant[name]:
  - vagrant up %name%
```

``` yml
up[project_x]:
  - =vagrant[project_x]
  - pstorm .
  - open http://local.project.url/
```

I'm getting this error:

```
Pla 0.4.0 by Richard Tuin - Coder's simplest workflow automation tool.

Running target "project":
    ✔ cd /home/renatomefi/Workspace/Enrise/%name%
Traceback (most recent call last):
  File "/usr/bin/pla", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/pla/__init__.py", line 6, in main
    pla()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pla/pla.py", line 64, in pla
    runResult = targetRunner.run(target, context.args)
  File "/usr/lib/python2.7/site-packages/pla/pla.py", line 99, in run
    error = self.run(command[1:], args, error)
  File "/usr/lib/python2.7/site-packages/pla/pla.py", line 83, in run
    if len(self.plafile[target]['arguments']) > len(args):
KeyError: 'vagrant[name]'
```

**Comment by rtuin** [comment]
Hey @renatomefidf, sorry for the late response. Apparently I don't get notifications for all of my repos.

No this is currently not possible, as mentioned in the disclaimer here: http://rtuin.github.io/pla/#linking-targets

Although a work-around, this would work:

``` yaml
vagrant[name]:
  - echo Hello %name%

up[name]:
  - =vagrant

```

The key is to give the both targets the same parameter name.

**Comment by rtuin** [comment]
@renatomefidf would this work for you?

**Comment by renatomefi** [comment]
Hello Richard, I did a bit of duplication but its fine!
Sorry for not keeping track of the issue

Pla is awesome! :D

**Comment by rtuin** [comment]
Thanks man!
